name: scOmnom_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10

  # Core scientific stack
  - scanpy
  - anndata
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - joblib
  - kneed
  - typer
  - scrublet
  - h5py
  - scikit-learn
  - igraph
  - python-igraph
  - leidenalg
  - pytest
  - pydantic
  - psutil

  # GPU-enabled PyTorch (official)
  - pytorch
  - pytorch-cuda=11.8

  - pip
  - pip:
      - umap-learn
      - scanorama
      - pyliger
      - harmonypy
      - scvi-tools
      - scib-metrics
