name: scOmnom_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python
  - python=3.11
  - setuptools

  # Numeric stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - h5py
  - scikit-learn
  - psutil

  # Scanpy ecosystem
  - scanpy
  - anndata
  - zarr
  - igraph
  - python-igraph
  - leidenalg
  - scrublet
  - kneed
  - typer
  - pydantic
  - bbknn

  # PyTorch / Lightning
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning

  # GPU acceleration:
  # On macOS: Metal/MPS enabled automatically. Comment out or remove the next line (pytorch-cuda)
  # On Linux (NVIDIA GPU) keep the next line to install pytorch-cuda.
  - pytorch-cuda=12.4

  # Testing
  - pytest

  # Pip packages
  - pip
  - pip:
      - pip>=23
      - setuptools>=69
      - wheel>=0.42
      - umap-learn
      - scvi-tools
      - scanorama
      - harmonypy
      - scib-metrics
      - types-pytz
      - celltypist
      - requests
