name: scOmnom_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python
  - python=3.11
  - setuptools

  # Numeric stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - h5py
  - scikit-learn
  - psutil

  # Scanpy ecosystem
  - scanpy
  - anndata
  - zarr
  - igraph
  - python-igraph
  - leidenalg
  - scrublet
  - kneed
  - typer
  - pydantic
  - bbknn

  # PyTorch / Lightning
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning

  # GPU acceleration:
  # On macOS: Metal/MPS enabled automatically.
  # On Linux (NVIDIA GPU) uncomment the next line.
  # - pytorch-cuda=12.1

  # Testing
  - pytest

  # Pip packages
  - pip
  - pip:
      - pip>=23
      - setuptools>=69
      - wheel>=0.42
      # GPU acceleration:
      # On macOS: Metal/MPS enabled automatically.
      # On Linux (NVIDIA GPU) uncomment the next lines.
      #- "jax[cuda12]"
      #- -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - umap-learn
      - scvi-tools
      - scib-metrics
      - types-pytz
      - celltypist
      - requests
