name: scOmnom_env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python
  - python=3.10
  - setuptools=69.5.1

  # Numeric stack
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - h5py
  - scikit-learn
  - psutil

  # Scanpy ecosystem
  - scanpy
  - anndata=0.11.4
  - zarr
  - igraph
  - python-igraph
  - leidenalg
  - scrublet
  - kneed
  - typer
  - pydantic
  - bbknn

  # PyTorch / Lightning
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-lightning=1.9.5

  # GPU acceleration:
  # On macOS: Metal/MPS enabled automatically.
  # On Linux (NVIDIA GPU) uncomment the next line.
  # - pytorch-cuda=11.7

  # Testing
  - pytest

  # Pip packages
  - pip
  - pip:
      - pip>=23
      - setuptools>=69
      - wheel>=0.42

      - umap-learn
      - scanorama
      - harmonypy
      - scvi-tools==1.3.3
      - scib-metrics
      - types-pytz
      - celltypist
      - requests
