name: scOmnom_env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python
  - python=3.10
  - setuptools=69.5.1

  # Numeric stack
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - h5py
  - scikit-learn
  - psutil

  # Scanpy ecosystem
  - scanpy
  - anndata
  - igraph
  - python-igraph
  - leidenalg
  - scrublet
  - kneed
  - typer
  - pydantic
  - bbknn
  - pytorch::pytorch=2.0.1
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2
  # # GPU ACCELERATION:
  # # ON A MAC: AUTO ENABLED (METAL)
  # # ON LINUX (NVIDIA GPU A100) - UNCOMMENT THIS LINE (ALSO ON HPC)
  # # - pytorch::pytorch-cuda=12.1

  # Testing
  - pytest

  # Pip packages
  - pip
  - pip:
      - pip>=23
      - setuptools>=69
      - wheel>=0.42

      - umap-learn
      - scanorama
      - harmonypy
      - scvi-tools
      - scib-metrics
      - types-pytz