name: scOmnom_env

channels:
  # Keep this ordering to make sure PyTorch + CUDA resolve cleanly
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python / tooling
  - python=3.11
  - pip
  - setuptools
  - wheel
  - cython

  # Numeric stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - h5py
  - scikit-learn
  - psutil

  # Scanpy ecosystem
  - scanpy
  - anndata
  - zarr
  - igraph
  - python-igraph
  - leidenalg
  - scrublet
  - kneed
  - typer
  - pydantic
  - bbknn
  - gseapy

  # PyTorch / Lightning
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning

  # GPU acceleration:
  # On macOS: Metal/MPS enabled automatically. Comment out or remove the next line (pytorch-cuda)
  # On Linux (NVIDIA GPU) keep the next line to install pytorch-cuda. (adjust version as needed)
  - pytorch-cuda=12.4

  # Testing
  - pytest

  # These packages seem to install more stable from pip
  - pip:
      - scvi-tools
      - scanorama
      - harmonypy
      - scib-metrics
      - celltypist
      - decoupler
      - umap-learn
      - requests
      - types-pytz